wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.7
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690488797.101468
    t:
      1:
      - 1
      - 5
      - 9
      - 21
      - 41
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 21
      - 41
      - 53
      - 55
      - 77
      - 103
      3:
      - 1
      - 2
      - 7
      - 23
      4: 3.10.12
      5: 0.15.7
      8:
      - 1
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: val/acc
      5: 1
      6:
      - 1
    - 1: val/auroc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/acc
      5: 1
      6:
      - 1
    - 1: train/auroc
      5: 1
      6:
      - 1
    - 1: parameters/graph_26Wc._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26Wc.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26Wc.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26Wc_2._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26Wc_2.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26Wc_2.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1_2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1_2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1_2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1_2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1_2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc1_2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_3\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_3\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_3\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_3\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_3\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26bn_3\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc3\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc3\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc3\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc3\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc3\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc3\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc4\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc4\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc4\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc4\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc4\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_26fc4\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc4\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc4\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc4\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc4\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc4\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc4\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc3\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc3\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc3\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc3\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc3\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc3\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_3\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_3\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_3\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_3\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_3\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_3\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1_2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1_2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1_2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1_2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1_2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1_2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn_2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26Wc_2._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26Wc_2.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26Wc_2.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26fc1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_26Wc._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_26Wc.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_26Wc.bins
      5: 1
      6:
      - 1
    - 1: test/loss
      5: 1
      6:
      - 1
    - 1: test/acc
      5: 1
      6:
      - 1
    - 1: test/auroc
      5: 1
      6:
      - 1
n_hidden_sets:
  desc: null
  value: 128
n_hidden_sets_2:
  desc: null
  value: 128
n_elements:
  desc: null
  value: 64
n_elements_2:
  desc: null
  value: 64
d:
  desc: null
  value: 141
d_2:
  desc: null
  value: 233
n_classes:
  desc: null
  value: 2
class_weights:
  desc: null
  value:
  - 0.8221949724095647
  - 0.17780502759043526
