python scripts/molnet_test_runner.py pdbbind-custom msr2 --monitor loss --splitter random --n 4 --max-epochs 150 --project pdbbind-hyperparam --batch-size 64 --n-hidden-sets 64 --n-hidden-sets 64 --n-elements 4 --n-elements 4
python scripts/molnet_test_runner.py pdbbind-custom msr2 --monitor loss --splitter random --n 4 --max-epochs 150 --project pdbbind-hyperparam --batch-size 32 --n-hidden-sets 64 --n-hidden-sets 64 --n-elements 4 --n-elements 4
python scripts/molnet_test_runner.py pdbbind-custom msr2 --monitor loss --splitter random --n 4 --max-epochs 150 --project pdbbind-hyperparam --batch-size 128 --n-hidden-sets 64 --n-hidden-sets 64 --n-elements 4 --n-elements 4
python scripts/molnet_test_runner.py pdbbind-custom msr2 --monitor loss --splitter random --n 4 --max-epochs 150 --project pdbbind-hyperparam --batch-size 64 --n-hidden-sets 64 --n-hidden-sets 64 --n-elements 8 --n-elements 8
python scripts/molnet_test_runner.py pdbbind-custom msr2 --monitor loss --splitter random --n 4 --max-epochs 150 --project pdbbind-hyperparam --batch-size 64 --n-hidden-sets 128 --n-hidden-sets 128 --n-elements 8 --n-elements 8
python scripts/molnet_test_runner.py pdbbind-custom msr2 --monitor loss --splitter random --n 4 --max-epochs 150 --project pdbbind-hyperparam --batch-size 64 --n-hidden-sets 128 --n-hidden-sets 128 --n-elements 16 --n-elements 16
python scripts/molnet_test_runner.py pdbbind-custom msr2 --monitor loss --splitter random --n 4 --max-epochs 150 --project pdbbind-hyperparam --batch-size 64 --n-hidden-sets 32 --n-hidden-sets 32 --n-elements 32 --n-elements 32
python scripts/molnet_test_runner.py pdbbind-custom msr2 --monitor loss --splitter random --n 4 --max-epochs 150 --project pdbbind-hyperparam --batch-size 64 --n-hidden-channels 64 --n-hidden-channels 32 --n-hidden-sets 64 --n-hidden-sets 64 --n-elements 4 --n-elements 4
python scripts/molnet_test_runner.py pdbbind-custom msr2 --monitor loss --splitter random --n 4 --max-epochs 150 --project pdbbind-hyperparam --batch-size 64 --n-hidden-channels 128 --n-hidden-channels 64 --n-hidden-sets 64 --n-hidden-sets 64 --n-elements 4 --n-elements 4
python scripts/molnet_test_runner.py pdbbind-custom msr2 --monitor loss --splitter random --n 4 --max-epochs 150 --project pdbbind-hyperparam --batch-size 64 --n-hidden-channels 16 --n-hidden-channels 8 --n-hidden-sets 64 --n-hidden-sets 64 --n-elements 4 --n-elements 4
