wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.7
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690467904.050178
    t:
      1:
      - 1
      - 5
      - 9
      - 21
      - 41
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 21
      - 41
      - 53
      - 55
      - 77
      - 103
      3:
      - 1
      - 2
      - 7
      - 23
      4: 3.10.12
      5: 0.15.7
      8:
      - 1
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: parameters/graph_3Wc._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3Wc.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3Wc.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3Wc_2._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3Wc_2.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3Wc_2.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1_2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1_2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1_2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1_2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1_2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc1_2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc2\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc2\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc2\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc2\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc2\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc2\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_3\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_3\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_3\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_3\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_3\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3bn_3\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc3\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc3\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc3\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc3\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc3\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc3\.bias.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc4\.weight._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc4\.weight.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc4\.weight.bins
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc4\.bias._type
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc4\.bias.values
      5: 1
      6:
      - 1
    - 1: parameters/graph_3fc4\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc4\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc4\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc4\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc4\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc4\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc4\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc3\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc3\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc3\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc3\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc3\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc3\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_3\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_3\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_3\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_3\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_3\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_3\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1_2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1_2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1_2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1_2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1_2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1_2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn_2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3Wc_2._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3Wc_2.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3Wc_2.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3fc1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3Wc._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3Wc.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3Wc.bins
      5: 1
      6:
      - 1
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: val/acc
      5: 1
      6:
      - 1
    - 1: val/auroc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/acc
      5: 1
      6:
      - 1
    - 1: train/auroc
      5: 1
      6:
      - 1
    - 1: test/loss
      5: 1
      6:
      - 1
    - 1: test/acc
      5: 1
      6:
      - 1
    - 1: test/auroc
      5: 1
      6:
      - 1
n_hidden_sets:
  desc: null
  value: 16
n_hidden_sets_2:
  desc: null
  value: 16
n_elements:
  desc: null
  value: 8
n_elements_2:
  desc: null
  value: 8
d:
  desc: null
  value: 141
d_2:
  desc: null
  value: 233
n_classes:
  desc: null
  value: 2
class_weights:
  desc: null
  value:
  - 1
  - 1
